# Generated by Django 5.0.7 on 2024-07-26 15:43

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_address_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(default="CH", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(default="8808", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_address",
            field=models.CharField(default="Seestrasse 80", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
