# Generated by Django 5.0.7 on 2024-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_remove_profile_address_profile_city_profile_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="images/default_profile_xffzir", upload_to="images/"
            ),
        ),
    ]
