# Generated by Django 5.0.7 on 2024-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("women", "Women"), ("men", "Men"), ("kids", "Kids")],
                default="women",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
